- name: Install DHCP daemon
  community.general.pacman:
    name: dhcpcd
    state: present

- name: Obtain ethernet interface name
  shell: ip link | grep -v lo | sed -r "s; ;;g" | cut -d':' -f2 | head -n1
  register: interface

- name: Enable DHCP daemon
  systemd:
    name: "dhcpcd@{{ interface.stdout }}"
    state: started
    enabled: yes
