- name: Install needed packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Download yay package manager
  become: yes
  become_user: nobody
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay

- name: Install yay package manager
  become: yes
  become_user: nobody
  shell: |
    cd /tmp/yay
    makepkg -si --noconfirm

- name: Install needed AUR packages
  become: yes
  become_user: nobody
  shell: |
    cd /tmp
    yay -S --noconfirm --buildir=/tmp {{ item }}
  loop: "{{ aur_packages }}"

- name: Add default user to docker group
  user:
    name: "{{ user_name }}"
    groups: docker
    append: yes
