- name: Install needed packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ desktop_packages }}"

- name: Start XFCE at login
  shell: "echo 'exec startxfce4' >> /home/{{ user_name }}/.xinitrc"


- name: Copy XFCE configuration
  copy:
    src: "{{ data_dir.stdout }}/xfce4"
    dest: "/home/{{ user_name }}/.config"

- name: Add default wallpaper
  copy:
    src: "{{ data_dir.stdout }}/wallpaper.jpg"
    dest: "/usr/share/backgrounds/xfce"
